### ISSUE TITLE
这个错误应该怎么解决？

### ISSUE THREAD

**Issue by Tamsiree** [ian-quinn/manicotti#2]
![image](https://user-images.githubusercontent.com/17683613/110448495-3721ad80-80fc-11eb-83fd-a575367af08f.png)

**Comment by ian-quinn** [comment]
感谢您的指出，这个大概率是资源定位错误，我已将AssemblyResolve的方法写到了仓库里，现在应该能顺利执行模型建立和门窗生成两个命令。第三方DLL加载的问题由来已久，Jeremy在社区也给出了比较完整的解决方案，可参考 [Proper way to handle App.config bindingRedirects in Revit Add-In](https://forums.autodesk.com/t5/revit-api-forum/proper-way-to-handle-app-config-bindingredirects-in-revit-add-in/td-p/5692149)。如果运行最新的仓库代码仍有问题，可尝试从以下方面解决：
- 确保代码中的AssemblyResolve方法执行正确
- 确保Teigha程序集的DLL文件和生成的插件文件（Manicotti.dll & .addin）均位于默认的Revit插件文件夹中。如没有可能需要手动拷贝。如加载仍出现问题，或可拷贝这些DLL到调试程序Revit.exe的目录下（依据DLL检索顺序而定）
- 确保对DLL文件有访问权限。在其属性的安全项中，如果有被禁用可能，应勾选解除锁定
- 删掉Teigha的所有引用和资源项，然后重新添加到项目中，清理并编译项目

**Comment by Tamsiree** [comment]
万分感谢

**Comment by ian-quinn** [comment]
*For those who encountered the same issue...*
Probably the reason is, the program gets confused as to where to find those DLL files. It is an old topic on the forum and Jeremy has provided mature workarounds: [Proper way to handle App.config bindingRedirects in Revit Add-In](https://forums.autodesk.com/t5/revit-api-forum/proper-way-to-handle-app-config-bindingredirects-in-revit-add-in/td-p/5692149). Thanks for pointing out and I've added `AssemblyResolve` method to the repo. In case of `System.IO.FileNotFoundException` persisting please refer to this checklist:
- Make sure the AssemblyResolve method works in the function that tries to use Teigha for text recognition.
- Make sure the TD_Mgd.dll assembly and its dependent .dll files are in the same folder containing the compiled add-in assembly and manifest file (Manicotti.dll & .addin in this case). If AssemblyResolve fails, you may need to put all Teigha libraries under the same directory with Revit.exe or other paths (according to the DLL load order).
- Make sure you have full access to those DLL files. Under certain circumstances the DLL files from cloud will be blocked, and you can uncheck it from the Property panel by right clicking the file.
- Remove then Add all DLL files and references. Clean and Rebuild the project.

**Comment by Yennutiebat** [comment]
Do I need a paid license for Teigha?

**Comment by ian-quinn** [comment]
Unfortunately yes. But there are many legacy versions of Teigha on the internet I think could be embedded in personal project (without higher version DWG support). Revit hasn't exposed API to access text info within imported DWG yet, before that, third party DLL is needed to process the text. That's why this repo can only be a toy project. I heard Bimorph is able to read text but I don't know how...
